// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronicPayments.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.PSE.Epayco.EPAYCO", b =>
                {
                    b.Property<Guid>("id_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("estado")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("factura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ref_payco")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .HasColumnType("text");

                    b.Property<string>("transactionID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("id_pago");

                    b.HasIndex("transactionID")
                        .IsUnique();

                    b.ToTable("EPAYCO");
                });

            modelBuilder.Entity("Domain.Entities.PSE.ZonaPagos.HISTORIALZP", b =>
                {
                    b.Property<Guid>("id_historial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("cod_estado_fin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("cod_estado_ini")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("contabilizado_cobol_ok")
                        .HasColumnType("boolean");

                    b.Property<string>("descrip_estado_fin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("descrip_estado_ini")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("detalle_cobol_fin")
                        .HasColumnType("text");

                    b.Property<string>("detalle_cobol_ini")
                        .HasColumnType("text");

                    b.Property<string>("detalle_pago")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("estado_cobol_fin")
                        .HasColumnType("text");

                    b.Property<string>("estado_cobol_ini")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fecha_ini")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("hora_fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("hora_ini")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("id_pago")
                        .HasColumnType("uuid");

                    b.Property<string>("json_respuesta")
                        .HasColumnType("jsonb");

                    b.Property<string>("origen_cambio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("ticket_cobol_ok")
                        .HasColumnType("boolean");

                    b.HasKey("id_historial");

                    b.HasIndex("id_pago");

                    b.ToTable("HISTORIALZP");
                });

            modelBuilder.Entity("Domain.Entities.PSE.ZonaPagos.INTENTOSZP", b =>
                {
                    b.Property<Guid>("id_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("estado_intento")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateOnly?>("fecha_intento")
                        .HasColumnType("date");

                    b.Property<decimal>("flt_total_con_iva")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<decimal>("flt_valor_iva")
                        .HasColumnType("decimal(16, 2)");

                    b.Property<TimeOnly?>("hora_intento")
                        .HasColumnType("time without time zone");

                    b.Property<int>("int_id_comercio")
                        .HasColumnType("integer");

                    b.Property<int>("int_modalidad")
                        .HasColumnType("integer");

                    b.Property<int>("numero_ticket_cobol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("numero_ticket_cobol"));

                    b.Property<string>("str_apellido_cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("str_clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("str_descripcion_pago")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_email")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_id_cliente")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("str_id_pago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("str_nombre_cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("str_opcional1")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_opcional2")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_opcional3")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_opcional4")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_opcional5")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("str_telefono_cliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("str_tipo_id")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("str_usuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("id_pago");

                    b.HasIndex("str_id_pago");

                    b.ToTable("INTENTOSZP");
                });

            modelBuilder.Entity("Domain.Entities.Recaudos.RECAUDOSBANCOS", b =>
                {
                    b.Property<Guid>("id_recaudo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("codigo_comercio_recaudo")
                        .HasColumnType("integer");

                    b.Property<int>("codigo_estado_recaudo")
                        .HasColumnType("integer");

                    b.Property<int>("codigo_proveedor_recaudo")
                        .HasColumnType("integer");

                    b.Property<string>("codigo_recaudo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("detalle_recaudo_cobol")
                        .HasColumnType("text");

                    b.Property<bool>("es_reversado")
                        .HasColumnType("boolean");

                    b.Property<string>("estado_recaudo_cobol")
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_recaudo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_reverso_recaudo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id_transaccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("json_notificacion_recaudo")
                        .HasColumnType("jsonb");

                    b.Property<bool?>("recaudo_contabilizado_ok")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ticket_cobol_ok")
                        .HasColumnType("boolean");

                    b.Property<decimal>("total_recaudo")
                        .HasColumnType("decimal(16, 2)");

                    b.HasKey("id_recaudo");

                    b.HasIndex("codigo_recaudo");

                    b.ToTable("RECAUDOSBANCOS");
                });

            modelBuilder.Entity("Domain.Entities.PSE.ZonaPagos.HISTORIALZP", b =>
                {
                    b.HasOne("Domain.Entities.PSE.ZonaPagos.INTENTOSZP", "intentos_zp")
                        .WithMany()
                        .HasForeignKey("id_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("intentos_zp");
                });
#pragma warning restore 612, 618
        }
    }
}
